# Generated by Django 5.0.6 on 2024-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcapfile',
            name='namespace',
        ),
        migrations.DeleteModel(
            name='Namespace',
        ),
        migrations.DeleteModel(
            name='PcapFile',
        ),
    ]
